meetup_finder/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', TemplateView.as_view(template_name="meetup_finder/home.html")),
    #path('', include('allauth.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('meetup_finder_app.urls')),
]

meetup_finder_app/urls.py
from django.urls import path

from . import views
from django.views.generic import TemplateView

from django.urls import reverse
from django.views import generic
from django.conf.urls import include


app_name = 'meetup_finder_app'
urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('newevent/', views.NewEventView, name="newevent"),
    path('createEvent/', views.createEvent, name = 'createEvent'),
    path('accounts/profile/', views.WelcomeView, name="dashboard"),
    path('dashboard/', views.WelcomeView, name="dashboard"),
    path('upcoming/', views.UpcomingView.as_view(), name="upcoming"),
    path('<int:pk>', views.DetailView.as_view(), name = "detail"),
    path('single_map_vew/', views.SingleEventView, name="eventView"),
    path('signin2/',views.Sign2, name="signin2"),
    path('profile/',views.Uprofile, name="uProfile"),
    path('showInterest/', views.showInterest, name="show_interest"),
    path('revokeInterest/', views.revokeInterest, name="revoke_interest"),
    path('profiles/<int:user_id>',views.singleProfileView, name="singleProfile"),
    path('addFriend/',views.addFriend, name = 'addFriend'),
    path('removeFriend/',views.removeFriend, name = 'removeFriend'),
    path('requestFriend/',views.requestFriend, name = 'requestFriend'),
    path('rejectFriend/',views.rejectFriend, name = 'rejectFriend'),
    path('rescindRequest/',views.rescindRequest, name = 'rescindRequest'),
    path('friends/', views.FriendsView, name = 'FriendsView'),
    path('deleteEvent/', views.deleteEvent, name="delete_event"),
    path('', views.HomeView.as_view(), name='home'),
]

meetup_finder_app/models.py
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from allauth.socialaccount.models import SocialAccount

class AppUser(models.Model):
    id = models.IntegerField(primary_key=True)
    django_user = models.OneToOneField(User,on_delete=models.CASCADE)
    friends = models.ManyToManyField("self")
    # Wehn someone adds someone else they are put into requested friends, and if they are accepted
    # they are put into the friends field
    requested_friends = models.ManyToManyField("self", symmetrical = False)
    def __str__(self):
        return str(self.id)


class Event(models.Model):
    event_date = models.DateTimeField('event date')
    # need to add event name field sometime soon
    event_description = models.CharField(max_length=200)
    event_organizer = models.ForeignKey(User,related_name="owner",on_delete=models.CASCADE)
    event_location = models.CharField(max_length=200)
    event_name = models.CharField(max_length=200)
    lat = models.FloatField(default=38.036411)
    lng = models.FloatField(default=-78.502455)

    interested_users = models.ManyToManyField(User)

    def __str__(self):
        return self.event_description
    def coming_up(self):
        now = timezone.now()
        # maybe update this to refine including evnts that are ongoing (like a few hours past instead of a day)
        return now + datetime.timedelta(days=7) >= self.event_date >= (now - datetime.timedelta(days=1))

    def all_users(self):
        return self.interested_users.all()

    coming_up.admin_order_field = 'event_date'
    coming_up.boolean = True
    coming_up.short_description = 'Coming up soon?'

meetup_finder_app/views.py
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404


# Create your views here.

from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.utils import timezone

from django.urls import reverse
from django.views import generic
from django.views.generic.base import TemplateView
from .models import Event, AppUser
from django.contrib.auth.models import User
from allauth.socialaccount.models import SocialAccount


class HomeView(TemplateView):
    template_name = 'meetup_finder_app/home.html'


def CreateUser(user):
    print("Creating New User")
    try:
        social_account = SocialAccount.objects.filter(user_id=user.id)[0]
        new_user = AppUser(id=user.id,django_user=user)
        new_user.save()
    finally:
        pass

def WelcomeView(request):
    if len(AppUser.objects.filter(id=request.user.id)) == 0:
        CreateUser(request.user)
    template_name = 'meetup_finder_app/dashboard.html'
    return render(request, template_name)
    # template_name = 'meetup_finder_app/userProfile.html'

def FriendsView(request):
    if len(AppUser.objects.filter(id=request.user.id)) == 0:
        CreateUser(request.user)
    template_name = 'meetup_finder_app/friends.html'
    AUser = AppUser.objects.get(id = request.user.id)

    return render(request, template_name, context = {'friends_list':AUser.friends.all, 'requested_list':AUser.requested_friends.all})

def SingleEventView(request):
    template_name = 'meetup_finder_app/single_event_view.html'
    return render(request, template_name, context={"event":{"lat":38.028212,"lng":-78.511077}})

class IndexView(generic.ListView):
    template_name = 'meetup_finder_app/index.html'


    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Event.objects.filter(event_date__lte=timezone.now()).order_by('-event_date')[:5]


def NewEventView(request):
    template_name = 'meetup_finder_app/Updated_New_Event.html'
    return render(request,template_name)
def Sign2(request):
    template_name = 'meetup_finder_app/signin2.html'
    return render(request,template_name)
def Uprofile(request):
    template_name = 'meetup_finder_app/userProfile.html'
    if len(AppUser.objects.filter(id=request.user.id)) == 0:
        CreateUser(request.user)

    try:
        profile_picture = SocialAccount.objects.get(user_id=request.user.id).extra_data['picture']
    except:
        profile_picture = ""

    return render(request, template_name, context={"profile_picture":profile_picture})
   
    
def createEvent(request):
    newEvent = Event()
    newEvent.event_name = request.POST['event_name_text']
    newEvent.event_date = request.POST['event_time'] 
    newEvent.event_organizer = request.user
    newEvent.event_description = request.POST['detail_text']
    newEvent.event_location = request.POST['address']
    newEvent.lat = request.POST['lat']
    newEvent.lng = request.POST['lng']

    #newEvent.comment_text = request.POST['commented_text']
    #newComment.comment_name = request.POST['name']
    
    
    newEvent.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
    return HttpResponseRedirect(reverse('meetup_finder_app:detail',kwargs={'pk':newEvent.id}))

def deleteEvent(request):
    event = Event.objects.get(id=request.POST['Event'])
    if event:
        event.delete()
    return HttpResponseRedirect(reverse('meetup_finder_app:dashboard'))


def showInterest(request):

    userid = request.POST['User']
    eventid = request.POST['Event']

    event = Event.objects.get(id=eventid)
    user = User.objects.get(id=userid)

    event.interested_users.add(user)

    event.save()
    return HttpResponseRedirect(reverse('meetup_finder_app:detail',kwargs={'pk':eventid}))

def revokeInterest(request):

    userid = request.POST['User']
    eventid = request.POST['Event']

    event = Event.objects.get(id=eventid)
    user = User.objects.get(id=userid)

    event.interested_users.remove(user)

    print(user.event_set.all())

    event.save()
    return HttpResponseRedirect(reverse('meetup_finder_app:detail',kwargs={'pk':eventid}))

def singleProfileView(request, user_id):
    p = AppUser.objects.get(id=user_id)
    friends = AppUser.objects.get(id = request.user.id).friends
    AUser = AppUser.objects.get(id = request.user.id)
    context = {
        'profile': AppUser.objects.get(id=user_id),
        'friends': AppUser.objects.get(id = request.user.id).friends,
        'requested_friends': p.requested_friends,
        'AUser': AUser,
        'user_id': user_id,
    }

    template_name = ''
    if p in friends.all():
        template_name = 'meetup_finder_app/singleFriendView.html'
    else:
        template_name = 'meetup_finder_app/singleProfileView.html'


    return render(request, template_name, context)



def removeFriend(request):
    user_profile = AppUser.objects.get(id=request.POST['User'])
    friend_profile = AppUser.objects.get(id=request.POST['Friend'])
    user_profile.friends.remove(friend_profile)
    user_profile.save()
    friend_profile.save()
    return HttpResponseRedirect(reverse('meetup_finder_app:singleProfile',kwargs={'user_id':friend_profile.id}))

def requestFriend(request):
    user_profile = AppUser.objects.get(id=request.POST['User'])
    friend_profile = AppUser.objects.get(id=request.POST['Friend'])
    friend_profile.requested_friends.add(user_profile)
    friend_profile.save()
    user_profile.save()
    return HttpResponseRedirect(reverse('meetup_finder_app:singleProfile',kwargs={'user_id':friend_profile.id}))

def addFriend(request):
    user_profile = AppUser.objects.get(id=request.POST['User'])
    friend_profile = AppUser.objects.get(id=request.POST['Friend'])
    user_profile.friends.add(friend_profile)
    user_profile.requested_friends.remove(friend_profile)
    user_profile.save()
    friend_profile.save()
    return HttpResponseRedirect(reverse('meetup_finder_app:FriendsView'))

def rejectFriend(request):
    user_profile = AppUser.objects.get(id=request.POST['User'])
    friend_profile = AppUser.objects.get(id=request.POST['Friend'])
    user_profile.requested_friends.remove(friend_profile)
    user_profile.save()
    friend_profile.save()
    return HttpResponseRedirect(reverse('meetup_finder_app:FriendsView'))

def rescindRequest(request):
    user_profile = AppUser.objects.get(id=request.POST['User'])
    friend_profile = AppUser.objects.get(id=request.POST['Friend'])
    friend_profile.requested_friends.remove(user_profile)
    friend_profile.save()
    user_profile.save()
    return HttpResponseRedirect(reverse('meetup_finder_app:singleProfile',kwargs={'user_id':friend_profile.id}))


class UpcomingView(generic.ListView):
    template_name = 'meetup_finder_app/upcoming.html'
    #context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the closest 5 events.
        """
        return Event.objects.filter(event_date__gte=timezone.now()).order_by('event_date')[:5]

class DetailView(generic.DetailView):
    model = Event
    template_name = 'meetup_finder_app/detail.html'

meetup_finder_app/templates/meetup_finder_app/NewEvent.html
{%  extends 'meetup_finder_app/main.html' %}

{% block content %}

{% load static %}

<h1>Create Event Below</h1>
   
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="row">

      <div class="col-md-5">
        <div class="card card-body">
        <form action="{% url 'meetup_finder_app:createEvent'  %}" method="post">
        {% csrf_token %}
        <label>Event Name:</label><br>
        <input type="text" id="event_name_text" name="event_name_text"><br>
        <label>Location (address):</label>
        <input type="text" id="address" name="address"><br>
        <input type="submit" class="btn btn-primary" value="Publish Event">
        </form>
        <label>Description:</label><br>
        <input type="text" id='detail_text' name="detail_text"><br>
        <label>Date:</label>
        <input type="datetime-local" id="event_time"
          name="event_time"><br>
      </div>
    </div>
   </body>

   {% endblock %}

   

meetup_finder_app/templates/meetup_finder_app/dashboard.html
{%  extends 'meetup_finder_app/main.html' %}
{% load account %}

<!-- {% user_display user %} -->
{% load static %}

<head>
    <meta charset="utf-8">
    <title>{% block title %}KYSA Meetup Finder{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'test/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'test/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'test/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'test/style.css' %}">


    {% block stylesheet %}{% endblock %}
</head>

{% block content %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
        .hover2:hover{
            background-color: #e44c65;
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
    
</head>

<body>


    <main role="main">

        <section class="jumbotron text-center" style ="background-image: url('../../static/images/UVA map.jpg');">

        <div  style=" background: rgb(255, 255, 255); padding-top: 20px; height: 75%; margin: auto; width: 50%; padding: 10px;">
            <div class="container">
                <h1 style="text-transform: capitalize;"><span> Welcome {% user_display user %} to KYSA </span></h1>
                <p class="lead text-muted">Click on <a href="{% url 'meetup_finder_app:upcoming' %}"
                        class="smoothScroll" style="color: #e44c65;"><span>Explore</span></a> in the Navigation Bar to
                    view all events!</p>
                <p>

                    <a href="{% url 'meetup_finder_app:newevent' %}"  style="background-color: #e44c65;" class="btn btn-secondary my-2">Create an Event</a>
                    <a href="{% url 'meetup_finder_app:FriendsView' %}" style="background-color: #e44c65;" class="btn btn-secondary my-2">Your Friends</a>
                </p>
            </div>
    </section>


        <div class="album py-5 bg-light">
            <div class="container">
                <h2>Your Upcoming Events:</h2>
                <br>
                <div class="row">

                    {% for event in user.event_set.all %}
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <div class="card-body">
                                <h1 id="firstHeading" class="firstHeading">{{ event.event_name }}</h1>
                                <div id="bodyContent">
                                    <hr>
                                    <h5>By:</h5>
                                    <p style= "text-transform: capitalize;"> {{ event.event_organizer }}</p>
                                    <h6>Description:</h6>
                                    <p>{{ event.event_description }}</p>
                                    <h6>When:</h6>
                                    <p>{{ event.event_date }}</p>
                                    <br>
                                    <form action="{% url 'meetup_finder_app:detail' pk=event.id %}">
                                        <input class="btn btn-sm btn-outline-secondary hover2"  type="submit" value="Details" />
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    {%endfor%}
                </div>
            </div>
        </div>
        </div>


    </main>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

</html>


{% endblock %}

meetup_finder_app/templates/meetup_finder_app/detail.html
{% include 'meetup_finder_app/navbar.html' %}

{% include 'meetup_finder_app/single_event_view.html' %}

<div style = "padding-left:8px">

<h1 style="text-align: center;">{{ event.event_name }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <h4  style=" left: 0; margin-left: 100px;">Organizer:</h4>
    <p style=" left: 0; margin-left: 100px; text-transform: capitalize;"> {{event.event_organizer}} </p> 
    <h4  style=" left: 0; margin-left: 100px;">Description:</h4>
    <p style=" left: 0; margin-left: 100px;">{{event.event_description}}</p> 
    <h4  style=" left: 0; margin-left: 100px;">Date & Time:</h4>
    <p style=" left: 0; margin-left: 100px; ">{{event.event_date}}</p> 


    {% if user.is_authenticated %}



        {% if user in event.all_users%}

            <h5 style=" left: 0; margin-left: 100px;">You're going to this event! <br> See you on {{event.event_date}}! </h5><br>
            <form action="{% url 'meetup_finder_app:revoke_interest' %}" method="post">
            {% csrf_token %}
                <input type="hidden" id="eid" name="Event" value="{{event.id}}">
                <input type="hidden" id="uid" name="User" value="{{user.id}}">
                <input type="submit" class="btn btn-primary" value="No Longer Interested" style=" left: 0; margin-left: 100px;">
            </form>
        {% else %}
            <h5 style=" left: 0; margin-left: 100px;">Are you interested? <br> Let others know you're going!</h5><br>
            <form action="{% url 'meetup_finder_app:show_interest' %}" method="post">
            {% csrf_token %}
                <input type="hidden" id="eid" name="Event" value="{{event.id}}">
                <input type="hidden" id="uid" name="User" value="{{user.id}}">
                <input type="submit" class="btn btn-primary" value="Interested" style=" left: 0; margin-left: 100px;">
            </form>
        {% endif %}

        {% if event.event_organizer == user %}
        <form action="{% url 'meetup_finder_app:delete_event' %}" method="post">
        {% csrf_token %}
            <input type="hidden" id="eid" name="Event" value="{{event.id}}">
            <input type="hidden" id="uid" name="User" value="{{user.id}}">
            <input type="submit" class="btn btn-danger" value="Delete Event" style="position: absolute; right: 0; margin-right: 100px;">
        </form>

        {% endif %}

        <hr>
        <h5 style=" left: 0; margin-left: 100px;">Interested Users:</h5>
        <ul style="text-transform: capitalize;">
        {%for u in event.all_users%}
            {%if not user.id == u.id %}
            <li style=" left: 0; margin-left: 100px;"><a href = "{% url 'meetup_finder_app:singleProfile' u.id %}">{{u}}</a></li>
            {%endif%}
        {% endfor %}
        </ul>




    {% endif %}     

</div> 

meetup_finder_app/templates/meetup_finder_app/friends.html
{% extends 'meetup_finder_app/main.html' %}
{% load account socialaccount %}

<!-- {% user_display user %} -->
{% load static %}

<head>
    <meta charset="utf-8">
    <title>{% block title %}KYSA Meetup Finder{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'test/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'test/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'test/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'test/style.css' %}">


    {% block stylesheet %}{% endblock %}
</head>

{% block content %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Album example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
</head>

<body>


    <main role="main">

        <section class="jumbotron text-center">
            <div class="container">
                <h1><span>Your Friends </span></h1>
            </div>
        </section>


        {% if requested_list %}

        <h3 style=" left: 0; margin-left: 200px;">   Pending Friend Requests</h3>

        {% for r in requested_list %}

        <div style=" left: 0; margin-left: 200px;">
            <h5><a href="{% url 'meetup_finder_app:singleProfile' r.id %}" class="profile-link">
                {{r.django_user.first_name}} {{r.django_user.last_name}} </a> </h5>
        <form action="{% url 'meetup_finder_app:addFriend' %}" method="post">
                {% csrf_token %}
                <input type="hidden" id="fid" name="Friend" value="{{r.id}}">
                <input type="hidden" id="uid" name="User" value="{{user.id}}">
                <input type="submit" class="btn btn-sm btn-outline-secondary"
                value="Confirm Friend" >
            </form>
            <br>

            <form action="{% url 'meetup_finder_app:rejectFriend' %}" method="post">
                {% csrf_token %}
                <input type="hidden" id="fid" name="Friend" value="{{r.id}}">
                <input type="hidden" id="uid" name="User" value="{{user.id}}">
                <input type="submit" class="btn btn-sm btn-outline-secondary"
                value="Reject Friend">
            </form>

        </div>

        {% endfor %}
        {% endif %}

        <br>

        {% if friends_list %}
        <h4 style=" left: 0; margin-left: 200px;"> All Friends </h4>

        {%for u in friends_list%}
        <div class="container">
            <div class="nearby-user">
                <div class="row">
            
                        <li><a href="{% url 'meetup_finder_app:singleProfile' u.id %}" class="profile-link">
                                {{u.django_user.first_name}} {{u.django_user.last_name}} </a> </li>



                      <!--                       
                    <div class="col-md-3 col-sm-3">
                        <form action="{% url 'meetup_finder_app:removeFriend' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" id="uid" name="User" value="{{user.id}}">
                            <input type="hidden" id="fid" name="Friend" value="{{friend.id}}">
                            <input type="submit" class="btn btn-sm btn-outline-secondary" value="Remove Friend">
                        </form>
                      </div>
-->

                </div>

            </div>

            {% endfor %}
            {% endif %}
            </div>

            




            {% endblock %}

meetup_finder_app/templates/meetup_finder_app/multi_event_view.html
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDZJQ6RGoFJHdFW8gQc96N99L0tOHHJXk4&callback=initMap&libraries=&v=weekly" defer></script>
<div id="map" style="width:100%;height: 100%;"></div>


        <script>
            // Initialize and add the map
            function initMap() {        
                let locations = []

                {% for event in event_list %}
                    var content = `
                    <div id="content">
                        <div id="siteNotice"></div>
                        <h1 id="firstHeading" class="firstHeading">{{ event.event_name }}</h1> 
                        <div id="bodyContent"> 
                            <hr>
                            <h5>By:</h5>
                            <p>{{ event.event_organizer }}</p>
                            <h5>Description:</h5>
                            <p>{{ event.event_description }}</p>
                            <h5>When:</h5>
                            <p>{{ event.event_date }}</p>
                            <br>
                            <form action="{% url 'meetup_finder_app:detail' pk=event.id %}">
                                <input class="btn btn-sm btn-outline-secondary" type="submit" value="Details" />
                            </form>
                        </div>
                    </div>`

                    locations.push({ lat: {{event.lat}}, lng: {{event.lng}}, cont:content})
                {% endfor %}

                console.log(locations)

                map_center = {lat:0,lng:0}

                locations.map(o=> {
                    map_center.lat += o.lat;
                    map_center.lng += o.lng;
                })

                map_center.lat /= locations.length;
                map_center.lng /= locations.length;
        
                const map = new google.maps.Map(document.getElementById("map"), {
                    zoom: 15,
                    center: map_center,
                });
        
                locations.map(o=>{
                    let infowindow = new google.maps.InfoWindow({
                        content: o.cont,
                    });
                    let marker = new google.maps.Marker({
                        position: {lat:o.lat,lng:o.lng},
                        map: map,
                    });
                    marker.addListener("click", () => {
                        infowindow.open(map, marker);
                    });
                })

                map.setOptions({scrollwheel: false});
                
            }
        
        </script>

meetup_finder_app/templates/meetup_finder_app/welcome.html
{% load account %}
<!-- {% user_display user %} -->
{% load static %}
<head>
    <meta charset="utf-8">
    <title>{% block title %}Meetup Finder{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %}  
  </head>
  <body>

    {% block body %}  
    <section id="navbar">
      <nav class="navbar navbar-light bg-light justify-content-between">
          <a class="navbar-brand">
                <a href="" class="navbar-brand smoothScroll">Meetup Finder</a>
          </a>
              <ul class="nav navbar-header ml-auto" style="font-size: 20px;">
                <!-- <li><a href="" class="smoothScroll px-3"><span>Home</span></a></li> -->
                <form class="form-inline">
                  <input class="form-control mr-sm-2 px-3" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form> 
                <li><a href="{% url 'meetup_finder_app:account_login'%}" class="smoothScroll px-3"><span>{% user_display user %}'s Profile</span></a></li>
                <li><a href="{% url 'meetup_finder_app:upcoming' %}" class="smoothScroll px-3"><span>Explore</span></a></li>
              </ul>
      </nav>
</section>
    {% endblock body %}  
  </body>
<br>
<a href="{% url 'meetup_finder_app:upcoming' %}">Upcoming Events</a>
<p>My Events</p>
<br>
<a href="{% url 'meetup_finder_app:newevent' %}">Make an Event</a>